# Generated by Django 4.1.3 on 2022-11-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='no_of_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_rating',
            field=models.IntegerField(null=True),
        ),
    ]
