# Generated by Django 4.1.3 on 2022-11-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.BigIntegerField(default=0),
        ),
    ]
