# Generated by Django 4.1.3 on 2022-11-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_user_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rate_listing',
            field=models.CharField(default='', max_length=200),
        ),
    ]
