# Generated by Django 4.1.3 on 2022-11-20 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_user_rate_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tipoCuenta',
        ),
    ]
